"""
Django settings for arataproject project.

Generated by 'django-admin startproject' using Django 3.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path

# osが見つからないとエラーが出たので自分で追加
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-j9a_vx$bgj0)01jn+kkc61(n8n!ac!hwi$ptahk%g0n47y8z$b'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
# 実際にユーザーに後悔するときにはFalseにしないといけない

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'arataapp',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'anymail',
]
# Djangoは上から順番に見ていくのでログインページをカスタマイズするときはadminより前に持ってくる

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware'
]

# MIDDLEWAREにWHITENOISEを追加

ROOT_URLCONF = 'arataproject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True, # これをFalseにすると同じ位置のTemplateを参照しないらしい（未検証）
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'arataproject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/


STATIC_URL = '/static/'
# もとはstatic、自由に変更可能

#ホワイトノイズの設定を追加
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_STORAGR = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Login/Logout系

LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/mypage/'
LOGOUT_REDIRECT_URL = '/login/'

### MAIL設定

ANYMAIL = {
    "MAILGUN_API_KEY" : "8b4f65eeba8afa2ee4627fee314be681-dbdfb8ff-c4f5bf4c",
    "MAILGUN_SENDER_DOMAIN" : "sandbox1568eef212d54ae5b5fa32442d077d54.mailgun.org",
}
EMAIL_BACKEND = 'anymail.backends.mailgun.EmailBackend'
DEFAUL_FROM_EMAIL = "hondo@example.com"
SERVER_EMAIL = "server@example.com"


### USER設定
AUTH_USER_MODEL = 'arataapp.User'




### Project直下のStatic = adminページなどの編集
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]